# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-26 18:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('einkauf', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 4, 26, 18, 58, 58, 472625), editable=False),
        ),
        migrations.AlterField(
            model_name='booking',
            name='purchased',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 4, 26, 18, 58, 58, 471814), editable=False),
        ),
    ]
