# Generated by Django 2.2 on 2019-06-15 07:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('einkauf', '0004_auto_20180804_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 6, 15, 7, 17, 57, 739651), editable=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 6, 15, 7, 17, 57, 739060), editable=False),
        ),
    ]
